avaliacoes/urls.py
from django.urls import path
from . import views

app_name = 'avaliacoes'


urlpatterns = [
    path('', views.home, name='home'),
    path('criar_avaliacao/', views.criar_avaliacao, name='criar_avaliacao'),
    path('excluir_avaliacao/<int:avaliacao_id>/', views.excluir_avaliacao, name='excluir_avaliacao'),
    path('editar_avaliacao/<int:avaliacao_id>/', views.editar_avaliacao, name='editar_avaliacao'),
    path('avaliador_detalhes_avaliacao/<int:avaliacao_id>/', views.avaliador_detalhes_avaliacao, name='avaliador_detalhes_avaliacao'),
    path('distribuidor_detalhes_avaliacao/<int:avaliacao_id>/', views.distribuidor_detalhes_avaliacao, name='distribuidor_detalhes_avaliacao'),
    path('distribuidor_detalhes_avaliacao_arquivos/<int:avaliador_id>/<int:avaliacao_id>/', views.distribuidor_detalhes_avaliacao_arquivos, name='distribuidor_detalhes_avaliacao_arquivos'),
    path('exibir_criar_indicador/<int:avaliacao_id>/', views.exibir_criar_indicador, name='exibir_criar_indicador'),
    path('criar_indicador/<int:avaliacao_id>/', views.criar_indicador, name='criar_indicador'),
    path('editar_indicador/<int:indicador_id>/', views.editar_indicador, name='editar_indicador'),
    path('excluir_indicador/<int:indicador_id>/', views.excluir_indicador, name='excluir_indicador'),
    path('copiar_indicadores/<int:avaliacao_id>/', views.copiar_indicadores, name='copiar_indicadores'),
    path('exibir_copiar_indicadores/<int:avaliacao_id>/', views.exibir_copiar_indicadores,
         name='exibir_copiar_indicadores'),
    path('listar_avaliadores/', views.listar_avaliadores, name='listar_avaliadores'),
    path('enviar_capa/<int:avaliacao_id>/', views.enviar_capa, name='enviar_capa'),
    path('substituir_capa/<int:capa_id>/', views.substituir_capa, name='substituir_capa'),
    path('apagar_capa/<int:capa_id>/', views.apagar_capa, name='apagar_capa'),
    path('baixar_capa/<int:capa_id>/', views.baixar_capa, name='baixar_capa'),
    path('enviar_arquivo/<int:indicador_id>/', views.enviar_arquivo, name='enviar_arquivo'),
    path('substituir_arquivo/<int:arquivo_id>/', views.substituir_arquivo, name='substituir_arquivo'),
    path('apagar_arquivo/<int:arquivo_id>/', views.apagar_arquivo, name='apagar_arquivo'),
    path('baixar_arquivo/<int:arquivo_id>/', views.baixar_arquivo, name='baixar_arquivo'),
    path('baixar_arquivo_distribuidor/<int:arquivo_id>/', views.baixar_arquivo_distribuidor, name='baixar_arquivo_distribuidor'),
]

contas/urls.py
from django.urls import path
from . import views

app_name = 'contas'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('cadastro/', views.signup, name='cadastro'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('detalhes_usuario/<int:pk>/', views.detalhes_usuario, name='detalhes_usuario'),
    path('detalhes_usuario/', views.detalhes_usuario, name='detalhes_usuario')
]

sisavaliacao/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import include, path
from contas import views as contas_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', contas_views.login_view, name='home'),
    path('', include('contas.urls', namespace='contas')),
    path('avaliacoes/', include('avaliacoes.urls', namespace='avaliacoes'))
]

avaliacoes/models.py
from django.db import models
from contas.models import CustomUser

class Avaliacao(models.Model):
    nome = models.CharField(max_length=255)
    inscricao = models.CharField(max_length=255)
    data_criacao = models.DateTimeField(auto_now_add=True)
    distribuidor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='avaliacoes_criadas', limit_choices_to={'user_type': 'distribuidor'})
    avaliadores = models.ManyToManyField(CustomUser, related_name='avaliacoes', limit_choices_to={'user_type': 'avaliador'})

    def __str__(self):
        return self.nome

class Indicador(models.Model):
    DIMENSOES = (
        ('Organização Didático-Pedagógico', 'Organização Didático-Pedagógico'),
        ('Corpo Docente e Tutorial', 'Corpo Docente e Tutorial'),
        ('Infraestrutura', 'Infraestrutura'),
    )
    nome = models.CharField(max_length=255)
    dimensao = models.CharField(max_length=255, choices=DIMENSOES)
    avaliacao = models.ForeignKey(Avaliacao, on_delete=models.CASCADE, related_name='indicadores')

    def __str__(self):
        return self.nome

class ArquivoIndicador(models.Model):
    arquivo = models.FileField(upload_to='arquivos_indicadores/')
    indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE, related_name='arquivos')
    avaliador = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='arquivos_indicadores', limit_choices_to={'user_type': 'avaliador'})

    class Meta:
        unique_together = ('indicador', 'avaliador')


class CapaAvaliacao(models.Model):
    capa = models.FileField(upload_to='capas_avaliacoes/')
    avaliacao = models.ForeignKey(Avaliacao, on_delete=models.CASCADE, related_name='capas')
    avaliador = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='capas_avaliacoes', limit_choices_to={'user_type': 'avaliador'})

avaliacoes/forms.py
from django import forms
from .models import Avaliacao, Indicador, ArquivoIndicador, CapaAvaliacao
from contas.models import CustomUser

class AvaliacaoForm(forms.ModelForm):
    avaliadores = forms.ModelMultipleChoiceField(
        queryset=CustomUser.objects.filter(user_type='avaliador'),
        widget=forms.CheckboxSelectMultiple,
        label='Avaliadores',
        required=False
    )

    class Meta:
        model = Avaliacao
        fields = ('nome', 'inscricao', 'avaliadores')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['avaliadores'].label_from_instance = lambda obj: obj.name

    def clean(self):
        cleaned_data = super().clean()
        avaliadores = cleaned_data.get('avaliadores')
        if not avaliadores:
            self.add_error('avaliadores', 'Selecione pelo menos um avaliador.')

class IndicadorForm(forms.ModelForm):
    class Meta:
        model = Indicador
        fields = ('nome', 'dimensao')

class ArquivoIndicadorForm(forms.ModelForm):
    class Meta:
        model = ArquivoIndicador
        fields = ('arquivo', 'indicador', 'avaliador')

class CapaAvaliacaoForm(forms.ModelForm):
    class Meta:
        model = CapaAvaliacao
        fields = ('capa', 'avaliacao', 'avaliador')

avaliacoes/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Avaliacao, Indicador, ArquivoIndicador, CapaAvaliacao
from .forms import AvaliacaoForm, IndicadorForm, ArquivoIndicadorForm, CapaAvaliacaoForm
from contas.models import CustomUser
from django.http import HttpResponse
from django.http import FileResponse
from PyPDF2 import PdfMerger
from io import BytesIO




@login_required
def home(request):
    if request.user.user_type == 'distribuidor':
        avaliacoes = Avaliacao.objects.filter(distribuidor=request.user)
    else:
        avaliacoes = request.user.avaliacoes.all()
    return render(request, 'avaliacoes/home.html', {'avaliacoes': avaliacoes})

#avaliações
@login_required
def criar_avaliacao(request):
    if request.method == 'POST':
        form = AvaliacaoForm(request.POST)
        if form.is_valid():
            avaliacao = form.save(commit=False)
            avaliacao.distribuidor = request.user
            avaliacao.save()
            # Salvar o ID da avaliação criada em uma variável de sessão
            request.session['avaliacao_criada_id'] = avaliacao.id
            return redirect('avaliacoes:exibir_copiar_indicadores', avaliacao.id)
    else:
        form = AvaliacaoForm()
    return render(request, 'avaliacoes/criar_avaliacao.html', {'form': form})



@login_required
def excluir_avaliacao(request, avaliacao_id):
    avaliacao = get_object_or_404(Avaliacao, id=avaliacao_id)
    if request.user != avaliacao.distribuidor:
        messages.error(request, 'Você não tem permissão para excluir esta avaliação.')
        return redirect('avaliacoes:editar_avaliacao', avaliacao_id=avaliacao.id)
    # Excluir arquivos e capas relacionados
    for indicador in avaliacao.indicadores.all():
        for arquivo in indicador.arquivos.all():
            arquivo.delete()
        indicador.delete()
    for capa in avaliacao.capas.all():
        capa.delete()
    # Excluir avaliação
    avaliacao.delete()
    messages.success(request, 'Avaliação excluída com sucesso!')
    return redirect('avaliacoes:home')


@login_required
def editar_avaliacao(request, avaliacao_id):
    avaliacao = get_object_or_404(Avaliacao, id=avaliacao_id)
    if request.user != avaliacao.distribuidor:
        messages.error(request, 'Você não tem permissão para editar esta avaliação.')
        return redirect('avaliacoes:home')
    if request.method == 'POST':
        form = AvaliacaoForm(request.POST, instance=avaliacao)
        if form.is_valid():
            form.save()
            messages.success(request, 'Avaliação atualizada com sucesso!')
            return redirect('avaliacoes:distribuidor_detalhes_avaliacao', avaliacao.id)
    else:
        form = AvaliacaoForm(instance=avaliacao)
    indicadores_por_dimensao = {}
    for dimensao in Indicador.DIMENSOES:
        indicadores_por_dimensao[dimensao[0]] = Indicador.objects.filter(avaliacao=avaliacao, dimensao=dimensao[0])
    return render(request, 'avaliacoes/editar_avaliacao.html', {'form': form, 'avaliacao': avaliacao, 'indicadores_por_dimensao': indicadores_por_dimensao})


def listar_avaliacoes(request):
    if request.user.user_type == 'distribuidor':
        avaliacoes = Avaliacao.objects.filter(distribuidor=request.user)
    elif request.user.user_type == 'avaliador':
        avaliacoes = Avaliacao.objects.filter(avaliadores=request.user)
    else:
        avaliacoes = Avaliacao.objects.none()
    return avaliacoes


def listar_avaliadores(request):
    avaliadores = CustomUser.objects.filter(user_type='avaliador')
    return render(request, 'avaliacoes/listar_avaliadores.html', {'avaliadores': avaliadores})

@login_required
def avaliador_detalhes_avaliacao(request, avaliacao_id):
    avaliacao = get_object_or_404(Avaliacao, id=avaliacao_id)
    capa = CapaAvaliacao.objects.filter(avaliacao=avaliacao, avaliador=request.user).first()
    indicadores = Indicador.objects.filter(avaliacao=avaliacao)
    arquivos_indicadores = ArquivoIndicador.objects.filter(indicador__in=indicadores, avaliador=request.user)

    context = {
        'avaliacao': avaliacao,
        'capa': capa,
        'indicadores': indicadores,
        'arquivos_indicadores': arquivos_indicadores,
    }
    return render(request, 'avaliacoes/avaliador_detalhes_avaliacao.html', context)



@login_required
def distribuidor_detalhes_avaliacao(request, avaliacao_id):
    avaliacao = get_object_or_404(Avaliacao, id=avaliacao_id)
    indicadores = Indicador.objects.filter(avaliacao=avaliacao)
    avaliadores = CustomUser.objects.filter(avaliacoes=avaliacao)

    # Agrupa os indicadores por dimensão
    indicadores_por_dimensao = {}
    for indicador in indicadores:
        if indicador.dimensao not in indicadores_por_dimensao:
            indicadores_por_dimensao[indicador.dimensao] = []
        indicadores_por_dimensao[indicador.dimensao].append(indicador)

    context = {
        'avaliacao': avaliacao,
        'indicadores_por_dimensao': indicadores_por_dimensao,
        'avaliadores': avaliadores,
    }
    return render(request, 'avaliacoes/distribuidor_detalhes_avaliacao.html', context)

@login_required
def distribuidor_detalhes_avaliacao_arquivos(request, avaliador_id, avaliacao_id):
    avaliacao = get_object_or_404(Avaliacao, id=avaliacao_id)
    avaliador = get_object_or_404(CustomUser, id=avaliador_id)
    indicadores = Indicador.objects.filter(avaliacao=avaliacao)
    arquivos = ArquivoIndicador.objects.filter(indicador__in=indicadores, avaliador=avaliador)

    # Agrupa os indicadores por dimensão
    indicadores_por_dimensao = {}
    for indicador in indicadores:
        if indicador.dimensao not in indicadores_por_dimensao:
            indicadores_por_dimensao[indicador.dimensao] = []
        indicadores_por_dimensao[indicador.dimensao].append(indicador)

    context = {
        'avaliacao': avaliacao,
        'avaliador': avaliador,
        'indicadores_por_dimensao': indicadores_por_dimensao,
        'arquivos': arquivos,
    }
    return render(request, 'avaliacoes/distribuidor_detalhes_avaliacao_arquivos.html', context)

#indicadores
@login_required
def criar_indicador(request, avaliacao_id):
    avaliacao = get_object_or_404(Avaliacao, id=avaliacao_id)
    if request.user != avaliacao.distribuidor:
        messages.error(request, 'Você não tem permissão para criar indicadores nesta avaliação.')
        return redirect('avaliacoes:home')

    if request.method == 'POST':
        form = IndicadorForm(request.POST)
        if form.is_valid():
            # Cria um novo indicador com os dados do formulário
            nome = form.cleaned_data['nome']
            dimensao = form.cleaned_data['dimensao']
            Indicador.objects.create(nome=nome, dimensao=dimensao, avaliacao=avaliacao)
            messages.success(request, 'Indicador criado com sucesso!')
            return redirect('avaliacoes:criar_indicador', avaliacao_id=avaliacao.id)
    else:
        form = IndicadorForm()

    # Obtém os indicadores por dimensão
    indicadores = Indicador.objects.filter(avaliacao=avaliacao)
    indicadores_por_dimensao = {}
    for indicador in indicadores:
        if indicador.dimensao not in indicadores_por_dimensao:
            indicadores_por_dimensao[indicador.dimensao] = []
        indicadores_por_dimensao[indicador.dimensao].append(indicador)

    return render(request, 'avaliacoes/criar_indicador.html', {
        'avaliacao': avaliacao,
        'form': form,
        'indicadores_por_dimensao': indicadores_por_dimensao,
    })




@login_required
def exibir_criar_indicador(request, avaliacao_id):
    avaliacao = get_object_or_404(Avaliacao, id=avaliacao_id)
    if request.user != avaliacao.distribuidor:
        messages.error(request, 'Você não tem permissão para criar indicadores nesta avaliação.')
        return redirect('avaliacoes:home')

    indicadores = Indicador.objects.filter(avaliacao=avaliacao)
    indicadores_por_dimensao = {}
    for indicador in indicadores:
        if indicador.dimensao not in indicadores_por_dimensao:
            indicadores_por_dimensao[indicador.dimensao] = []
        indicadores_por_dimensao[indicador.dimensao].append(indicador)

    return render(request, 'avaliacoes/criar_indicador.html', {
        'avaliacao': avaliacao,
        'indicadores_por_dimensao': indicadores_por_dimensao,
    })

@login_required
def excluir_indicador(request, indicador_id):
    indicador = get_object_or_404(Indicador, id=indicador_id)
    if request.user != indicador.avaliacao.distribuidor:
        messages.error(request, 'Você não tem permissão para excluir este indicador.')
        return redirect('avaliacoes:home')
    if request.method == 'POST':
        # Excluir arquivos relacionados
        for arquivo in indicador.arquivos.all():
            arquivo.delete()
        # Excluir indicador
        indicador.delete()
        messages.success(request, 'Indicador excluído com sucesso!')
    return redirect('avaliacoes:criar_indicador', avaliacao_id=indicador.avaliacao.id)

@login_required
def editar_indicador(request, indicador_id):
    indicador = get_object_or_404(Indicador, id=indicador_id)
    if request.user != indicador.avaliacao.distribuidor:
        messages.error(request, 'Você não tem permissão para editar este indicador.')
        return redirect('avaliacoes:home')
    if request.method == 'POST':
        nome = request.POST.get('nome')
        if nome:
            indicador.nome = nome
            indicador.save()
            messages.success(request, 'Indicador atualizado com sucesso!')
    return redirect('avaliacoes:criar_indicador', avaliacao_id=indicador.avaliacao.id)

@login_required
def exibir_copiar_indicadores(request, avaliacao_id):
    avaliacao = get_object_or_404(Avaliacao, id=avaliacao_id)
    if request.user != avaliacao.distribuidor:

templates/avaliacoes/avaliador_detalhes_avaliacao.html
{% extends 'base.html' %}
{% load templatetags %}

{% block extrahead %}
    <style>
        input[type="file"] {
            display: none;
        }
        .custom-file-upload {
            border: 1px solid #ccc;
            display: inline-block;
            padding: 6px 12px;
            cursor: pointer;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        .box {
            background-color: #f8f8f8;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
        }

        .button-group {
            display: flex;
            align-items: center;
            margin-bottom: 5px;
        }

        .button-group h4 {
            margin-bottom: 0;
            padding-bottom: 1px;
        }

        .button-group a {
            display: inline-block;
            padding: 10px 15px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin-right: 10px;
        }

        .button-group .btn-baixar {
            background-image: linear-gradient(to bottom right, #3461eb, #5ec4bf);
            margin-left: auto;
            margin-bottom: 1px;
            padding-top: 5px;
            padding-bottom: 5px;
        }

        .btn-distribuidor, .btn-enviar-capa, .btn-enviar-arquivo, .btn-baixar-arquivo, .btn-substituir-arquivo, .btn-substituir-capa, .btn-baixar-capa {
          background-image: linear-gradient(to bottom right, #3461eb, #5ec4bf);
          padding-top:3px;
          padding-bottom:3px;
          padding-left:8px;
          padding-right:8px;
          border-radius:5px;
          color:white;
          text-decoration:none;
          border:none
        }

        .btn-apagar-arquivo, .btn-apagar-capa {
          background-color:red;
          padding-top:3px;
          padding-bottom:3px;
          padding-left:8px;
          padding-right:8px;
          border-radius:5px;
          color:white;
          text-decoration:none;
          border:none
        }

        .indicador-item {
          display:flex;
          align-items:center;
          justify-content:flex-start;
          margin-bottom:10px
        }

        .indicador-item span {
          flex-grow:1;
          border-bottom:dotted 1px black;
          margin-left:auto
        }

        form {
          display:inline-block
        }
    </style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="box">
        <h1>{{ avaliacao.nome }}</h1>
        <p>Inscrição: {{ avaliacao.inscricao }}</p>
        <p>Data de criação: {{ avaliacao.data_criacao }}</p>
        <div class="button-group">
          <a href="{% url 'contas:detalhes_usuario' pk=avaliacao.distribuidor.id %}" class="btn-distribuidor">{{ avaliacao.distribuidor.name }}</a>
        </div>
    </div>
    <div class="box">
      <h2>Capa da Avaliação</h2>
      {% if capa %}
      <div class="button-group">
              <button class="btn-baixar-capa" onclick="location.href='{% url 'avaliacoes:baixar_capa' capa.id %}'">Baixar Capa</button>
              <form action="{% url 'avaliacoes:substituir_capa' capa.id %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <label for="capa" class="btn-substituir-capa">Substituir Capa</label>
                  <input type="file" id="capa" name="capa" onchange="this.form.submit()">
              </form>
              <form action="{% url 'avaliacoes:apagar_capa' capa.id %}" method="post">
                  {% csrf_token %}
                  <input type="submit" value="Apagar Capa" class="btn-apagar-capa">
              </form>
          </div>
      {% else %}
        <div class="button-group">
            <label for="capa" class="btn-enviar-capa">Enviar Capa</label>
            <form action="{% url 'avaliacoes:enviar_capa' avaliacao.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" id="capa" name="capa" onchange="this.form.submit()">
            </form>
        </div>
      {% endif %}
    </div>
    <div class="box">
        <h2>Organização Didático-Pedagógico</h2>
        {% for indicador in indicadores %}
            {% if indicador.dimensao == 'Organização Didático-Pedagógico' %}
                <div class="indicador-item">
                    {{ indicador.nome }}
                    <span></span>
                    {% with arquivos_indicadores|get_arquivo_indicador:indicador as arquivo %}
                        {% if arquivo %}
                            <a href="{% url 'avaliacoes:baixar_arquivo' arquivo.id %}" class="btn-baixar-arquivo">Baixar Arquivo</a>
                            <form action="{% url 'avaliacoes:substituir_arquivo' arquivo.id %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <label for="{{ indicador.id }}" class="btn-substituir-arquivo">Substituir Arquivo</label>
                                <input type="file" id="{{ indicador.id }}" name="arquivo" onchange="this.form.submit()">
                            </form>
                            <form action="{% url 'avaliacoes:apagar_arquivo' arquivo.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Apagar Arquivo" class="btn-apagar-arquivo">
                            </form>
                        {% else %}
                            <form action="{% url 'avaliacoes:enviar_arquivo' indicador.id %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <label for="{{ indicador.id }}" class="btn-enviar-arquivo">Enviar Arquivo</label>
                                <input type="file" id="{{ indicador.id }}" name="arquivo" onchange="this.form.submit()">
                            </form>
                        {% endif %}
                    {% endwith %}
                </div>
            {% endif %}
        {% endfor %}
    </div>

    <div class="box">
        <h2>Corpo Docente e Tutorial</h2>
        {% for indicador in indicadores %}
            {% if indicador.dimensao == 'Corpo Docente e Tutorial' %}
                <div class="indicador-item">
                    {{ indicador.nome }}
                    <span></span>
                    {% with arquivos_indicadores|get_arquivo_indicador:indicador as arquivo %}
                        {% if arquivo %}
                            <a href="{% url 'avaliacoes:baixar_arquivo' arquivo.id %}" class="btn-baixar-arquivo">Baixar Arquivo</a>
                            <form action="{% url 'avaliacoes:substituir_arquivo' arquivo.id %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <label for="{{ indicador.id }}" class="btn-substituir-arquivo">Substituir Arquivo</label>
                                <input type="file" id="{{ indicador.id }}" name="arquivo" onchange="this.form.submit()">
                            </form>
                            <form action="{% url 'avaliacoes:apagar_arquivo' arquivo.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Apagar Arquivo" class="btn-apagar-arquivo">
                            </form>
                        {% else %}
                            <form action="{% url 'avaliacoes:enviar_arquivo' indicador.id %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <label for="{{ indicador.id }}" class="btn-enviar-arquivo">Enviar Arquivo</label>
                                <input type="file" id="{{ indicador.id }}" name="arquivo" onchange="this.form.submit()">
                            </form>
                        {% endif %}
                    {% endwith %}
                </div>
            {% endif %}
        {% endfor %}
    </div>

    <div class="box">
        <h2>Infraestrutura</h2>
        {% for indicador in indicadores %}
            {% if indicador.dimensao == 'Infraestrutura' %}
                <div class="indicador-item">
                    {{ indicador.nome }}
                    <span></span>
                    {% with arquivos_indicadores|get_arquivo_indicador:indicador as arquivo %}
                        {% if arquivo %}
                            <a href="{% url 'avaliacoes:baixar_arquivo' arquivo.id %}" class="btn-baixar-arquivo">Baixar Arquivo</a>
                            <form action="{% url 'avaliacoes:substituir_arquivo' arquivo.id %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <label for="{{ indicador.id }}" class="btn-substituir-arquivo">Substituir Arquivo</label>
                                <input type="file" id="{{ indicador.id }}" name="arquivo" onchange="this.form.submit()">
                            </form>
                            <form action="{% url 'avaliacoes:apagar_arquivo' arquivo.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Apagar Arquivo" class="btn-apagar-arquivo">
                            </form>
                        {% else %}
                            <form action="{% url 'avaliacoes:enviar_arquivo' indicador.id %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <label for="{{ indicador.id }}" class="btn-enviar-arquivo">Enviar Arquivo</label>
                                <input type="file" id="{{ indicador.id }}" name="arquivo" onchange="this.form.submit()">
                            </form>
                        {% endif %}
                    {% endwith %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/avaliacoes/distribuidor_detalhes_avaliacao.html
{% extends 'base.html' %}
{% block content %}
<style>
    .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
    }

    .box {
        background-color: #f8f8f8;
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 20px;
    }

    .button-group {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
    }

    .button-group a {
        display: inline-block;
        padding: 10px 15px;
        background-color: #4CAF50;
        color: white;
        text-decoration: none;
        border-radius: 5px;
        margin-right: 10px;
    }
</style>

<div class="container">
    <div class="box">
        <h1>{{ avaliacao.nome }}</h1>
        <p>Inscrição: {{ avaliacao.inscricao }}</p>
        <p>Data de criação: {{ avaliacao.data_criacao }}</p>

        <div class="button-group">
            <a href="{% url 'avaliacoes:editar_avaliacao' avaliacao.id %}">Editar detalhes Avaliação</a>
            <a href="{% url 'avaliacoes:criar_indicador' avaliacao.id %}">Editar Indicadores</a>
        </div>
    </div>
    <div class="box">
        <h2>Escolha um dos avaliadores desta avaliação para ver os arquivos dele</h2>
        <ul>
            {% for avaliador in avaliadores %}
                <div class="button-group a">
                    <a href="{% url 'avaliacoes:distribuidor_detalhes_avaliacao_arquivos' avaliador.id avaliacao.id %}">{{ avaliador.name }}</a>
                </div>

            {% endfor %}
        </ul>
    </div>
    <div class="box">
        <h2>Indicadores Por Dimensão</h2>
    </div>
    {% for dimensao, indicadores in indicadores_por_dimensao.items %}
        <div class="box">
            <h3>{{ dimensao }}</h3>
            {% for indicador in indicadores %}
                <h4>{{ indicador.nome }}</h4>
            {% endfor %}
        </div>
    {% endfor %}
</div>
{% endblock %}