avaliacoes/urls.py
from django.urls import path
from . import views

app_name = 'avaliacoes'


urlpatterns = [
    path('', views.home, name='home'),
    path('criar_avaliacao/', views.criar_avaliacao, name='criar_avaliacao'),
    path('excluir_avaliacao/<int:avaliacao_id>/', views.excluir_avaliacao, name='excluir_avaliacao'),
    path('editar_avaliacao/<int:avaliacao_id>/', views.editar_avaliacao, name='editar_avaliacao'),
    path('avaliador_detalhes_avaliacao/<int:avaliacao_id>/', views.avaliador_detalhes_avaliacao, name='avaliador_detalhes_avaliacao'),
    path('distribuidor_detalhes_avaliacao/<int:avaliacao_id>/', views.distribuidor_detalhes_avaliacao, name='distribuidor_detalhes_avaliacao'),
    path('distribuidor_detalhes_avaliacao_arquivos/<int:avaliador_id>/<int:avaliacao_id>/', views.distribuidor_detalhes_avaliacao_arquivos, name='distribuidor_detalhes_avaliacao_arquivos'),
    path('exibir_criar_indicador/<int:avaliacao_id>/', views.exibir_criar_indicador, name='exibir_criar_indicador'),
    path('criar_indicador/<int:avaliacao_id>/', views.criar_indicador, name='criar_indicador'),
    path('editar_indicador/<int:indicador_id>/', views.editar_indicador, name='editar_indicador'),
    path('excluir_indicador/<int:indicador_id>/', views.excluir_indicador, name='excluir_indicador'),
    path('copiar_indicadores/<int:avaliacao_id>/', views.copiar_indicadores, name='copiar_indicadores'),
    path('exibir_copiar_indicadores/<int:avaliacao_id>/', views.exibir_copiar_indicadores,
         name='exibir_copiar_indicadores'),
    path('listar_avaliadores/', views.listar_avaliadores, name='listar_avaliadores'),
    path('enviar_capa/<int:avaliacao_id>/', views.enviar_capa, name='enviar_capa'),
    path('substituir_capa/<int:capa_id>/', views.substituir_capa, name='substituir_capa'),
    path('apagar_capa/<int:capa_id>/', views.apagar_capa, name='apagar_capa'),
    path('baixar_capa/<int:capa_id>/', views.baixar_capa, name='baixar_capa'),
    path('enviar_arquivo/<int:indicador_id>/', views.enviar_arquivo, name='enviar_arquivo'),
    path('substituir_arquivo/<int:arquivo_id>/', views.substituir_arquivo, name='substituir_arquivo'),
    path('apagar_arquivo/<int:arquivo_id>/', views.apagar_arquivo, name='apagar_arquivo'),
    path('baixar_arquivo/<int:arquivo_id>/', views.baixar_arquivo, name='baixar_arquivo'),
    path('baixar_arquivo_distribuidor/<int:arquivo_id>/', views.baixar_arquivo_distribuidor, name='baixar_arquivo_distribuidor'),
]

contas/urls.py
from django.urls import path
from . import views

app_name = 'contas'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('cadastro/', views.signup, name='cadastro'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('detalhes_usuario/<int:pk>/', views.detalhes_usuario, name='detalhes_usuario'),
    path('detalhes_usuario/', views.detalhes_usuario, name='detalhes_usuario')
]

sisavaliacao/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import include, path
from contas import views as contas_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', contas_views.login_view, name='home'),
    path('', include('contas.urls', namespace='contas')),
    path('avaliacoes/', include('avaliacoes.urls', namespace='avaliacoes'))
]

contas/models.py
from django.contrib.auth.decorators import login_required
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = (
        ('avaliador', 'Avaliador'),
        ('distribuidor', 'Distribuidor'),
    )
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    formacao_academica = models.CharField(max_length=255)

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="customuser_set",
        related_query_name="customuser",
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="customuser_set",
        related_query_name="customuser",
    )

contas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2', 'user_type', 'name', 'email', 'formacao_academica')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'formacao_academica')

contas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUser
from django.contrib import messages
from django.contrib.auth import logout
from avaliacoes.views import listar_avaliacoes
from avaliacoes.models import Avaliacao
from django.contrib.auth.decorators import login_required


def logout_view(request):
    logout(request)
    return redirect('contas:login')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            print(f'Usuário salvo: {user.username}, tipo: {user.user_type}')
            login(request, user)
            print(f'Usuário autenticado: {request.user.is_authenticated}') # Imprime se o usuário está autenticado
            if user.user_type == 'distribuidor':
                return redirect('avaliacoes:home')
            else:
                return redirect('avaliacoes:home')
        else:
            print(form.errors)
    else:
        form = CustomUserCreationForm()
    return render(request, 'contas/cadastro.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        print(request.POST)  # Imprime o valor de request.POST
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        print(user) # Imprime o valor de user
        if user is not None:
            login(request, user)
            if user.user_type == 'distribuidor':
                return redirect('avaliacoes:home')
            else:
                return redirect('avaliacoes:home')
        else:
            messages.error(request, 'Nome de usuário ou senha incorretos')
    return render(request, 'contas/login.html')

def editar_perfil(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('detalhes_usuario')
    else:
        form = CustomUserChangeForm(instance=request.user)
    return render(request, 'contas/editar_perfil.html', {'form': form})


@login_required
def detalhes_usuario(request, pk=None):
    if pk:
        usuario = CustomUser.objects.get(pk=pk)
    else:
        usuario = request.user

    if request.user.user_type in ['distribuidor', 'avaliador']:
        if request.user.user_type == 'distribuidor':
            avaliacoes = Avaliacao.objects.filter(distribuidor=request.user)
            avaliacoes = avaliacoes.filter(avaliadores=usuario)
        else:
            avaliacoes = Avaliacao.objects.filter(avaliadores=request.user)
            avaliacoes = avaliacoes.filter(distribuidor=usuario)
    else:
        avaliacoes = listar_avaliacoes(request)

    return render(request, 'contas/perfil_detalhes.html', {'usuario': usuario, 'avaliacoes': avaliacoes})

templates/contas/cadastro.html
{% load static %}
{% block content %}
    <style>
        body {
            background-image: url("{% static 'images/fundologin.jpg' %}");
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <div class="paglogin-form-container">
        <div class="paglogin-form-box">
            <h1>Cadastro</h1>
            <form method="post" action="{% url 'contas:cadastro' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Cadastrar</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/contas/editar_perfil.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <div class="paglogin-form-container">
        <div class="paglogin-form-box">
            <h1>Editar Perfil</h1>
            <form method="post" action="{% url 'contas:editar_perfil' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Salvar</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/contas/login.html
{% load static %}
{% block content %}
    <style>
        body {
            background-image: url("{% static 'images/fundologin.jpg' %}");
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <div class="paglogin-form-container">
        <div class="paglogin-form-box">
            <h1>Login</h1>
            <form method="post" action="{% url 'contas:login' %}">
                {% csrf_token %}
                <label for="username">Nome de usuário:</label>
                <input type="text" name="username" id="username" required>
                <br>
                <label for="password">Senha:</label>
                <input type="password" name="password" id="password" required>
                <br>
                <button type="submit">Entrar</button>
            </form>
            <p>Não tem uma conta? <a href="{% url 'contas:cadastro' %}">Cadastre-se</a></p>
        </div>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/contas/perfil_detalhes.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <div class="paglogin-form-container">
        <div class="paglogin-form-box">
            <h1>Detalhes do Usuário</h1>
            <p><strong>Nome:</strong> {{ usuario.name }}</p>
            <p><strong>Tipo de usuário:</strong> {{ usuario.get_user_type_display }}</p>
            <p><strong>Email:</strong> {{ usuario.email }}</p>
            <p><strong>Formação acadêmica:</strong> {{ usuario.formacao_academica }}</p>
            {% if usuario == request.user %}
                <a class="geral" href="{% url 'contas:editar_perfil' %}">Editar perfil</a>
            {% endif %}
            <h2>Avaliações em comum</h2>
            <ul>
                {% for avaliacao in avaliacoes %}
                    {% if request.user.user_type == 'distribuidor' %}
                        <li><a href="{% url 'avaliacoes:distribuidor_detalhes_avaliacao_arquivos' usuario.id avaliacao.id %}">{{ avaliacao.nome }}</a></li>
                    {% elif request.user.user_type == 'avaliador' %}
                        <li><a href="{% url 'avaliacoes:avaliador_detalhes_avaliacao' avaliacao.id %}">{{ avaliacao.nome }}</a></li>
                    {% else %}
                        <li>{{ avaliacao.nome }}</li>
                    {% endif %}
                {% empty %}
                    <li>Nenhuma avaliação encontrada.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}