contas/urls.py
from django.urls import path
from . import views

app_name = 'contas'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('cadastro/', views.signup, name='cadastro'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('detalhes_usuario/<int:pk>/', views.detalhes_usuario, name='detalhes_usuario'),
    path('detalhes_usuario/', views.detalhes_usuario, name='detalhes_usuario')
]

sisavaliacao/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import include, path
from contas import views as contas_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', contas_views.login_view, name='home'),
    path('', include('contas.urls', namespace='contas')),
    path('avaliacoes/', include('avaliacoes.urls', namespace='avaliacoes'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Hotjar Tracking Code for my site -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3563720,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
    <title>Projeto Avaliação</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
    {% block extrahead %}{% endblock %}
</head>
<body class="{% if user.is_authenticated %}logado{% endif %} tudoestilo" style="background-image: url(
    {% if user.is_authenticated and user.user_type == 'avaliador' %}
        {% static 'images/fundoavaliador.jpg' %}
    {% elif user.is_authenticated %}
        {% static 'images/fundodistribuidor.jpg' %}
    {% else %}
        {% static 'images/login.jpg' %}
    {% endif %}
); background-size: cover; background-repeat: no-repeat;">
    <header class="base">
        <div class="base-gradient"></div>
        <nav class="base-nav">
            <a class="base-button" href="{% url 'contas:detalhes_usuario' request.user.pk %}">Perfil</a>
            {% if user.is_authenticated %}
                <a class="base-button" href="{% url 'avaliacoes:home' %}">Home</a>
                <a class="base-button" href="{% url 'contas:logout' %}">Deslogar</a>
            {% endif %}
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <script>
        function confirmDelete() {
            return confirm('Tem certeza que deseja deletar este item?');
        }
    </script>
</body>
</html>